### ISSUE TITLE
Exception Kodi x64 18 nightly on Win 10 x64

### ISSUE THREAD

**Issue by mgonzales71** [ratoaq2/service.subtitles.subliminal#1]
I just found this promising looking subtitle addon for kodi here on GitHub and it throws an exception when I try to use it.

Trying it on Windows x64 with Kodi x64 18 "Leia" june 9th nightly.

If you happen to still support this addon I would love to check it out!

Thanks!

Mario

```
18:21:16.976 T:4464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pkg_resources
                                            Traceback (most recent call last):
                                              File "E:\Kodi\portable_data\addons\service.subtitles.subliminal\service.py", line 30, in <module>
                                                from plugin import SubliminalPlugin
                                              File "E:\Kodi\portable_data\addons\service.subtitles.subliminal\resources\lib\plugin.py", line 11, in <module>
                                                from language import LanguageConverter
                                              File "E:\Kodi\portable_data\addons\service.subtitles.subliminal\resources\lib\language.py", line 3, in <module>
                                                from babelfish import Language, Country
                                              File "E:\Kodi\portable_data\addons\service.subtitles.subliminal\resources\lib\babelfish\__init__.py", line 20, in <module>
                                                from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
                                              File "E:\Kodi\portable_data\addons\service.subtitles.subliminal\resources\lib\babelfish\converters\__init__.py", line 6, in <module>
                                                from pkg_resources import iter_entry_points, EntryPoint
                                            ImportError: No module named pkg_resources
                                            -->End of Python script error report<--
18:21:17.057 T:10552   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.subliminal/?action=search&languages=English&preferredlanguage=Unknown

```

**Comment by ratoaq2** [comment]
I'm planning to update this plugin and I'll test it on win x64 in a few days. :+1:
